name:                weeder-false
version:             0.1.0.0
github:              "githubuser/weeder-false"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/weeder-false#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


executables:
  one:
    main:                Main.hs
    source-dirs:         one
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    - -hiedir=.hie/one
  two:
    main:                Main.hs
    source-dirs:         two
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    - -hiedir=.hie/two
